### ISSUE TITLE
Deriving Clone, Copy in RouterTarget Would Help

### ISSUE THREAD

**Issue by anlumo** [saschagrunert/yew-router#216]
Adding `Clone, Copy` to the `#[derive]` declaration generated by the `routes` macro would allow passing the enum values around in messages and be stored in components (for example for having a list of target routes for a menu). This would remove the need to list the routes multiple times in the code.

**Comment by saschagrunert** [comment]
Hey, thanks for the issue. The idea generally sounds good to me, do you want to propose a PR? :)
